export interface Product {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  price: string;
  description: string;
  longDescription: string;
  features: string[];
  specifications: Record<string, string>;
  image: string;
  badge?: string;
  inStock: boolean;
}

export const products: Product[] = [
  // Dispensers
  {
    id: "counter-top-dispenser",
    name: "Counter Top Dispenser",
    category: "Dispensers",
    subcategory: "Water Dispensers",
    price: "From AED 599",
    description: "Compact counter-top water dispenser for homes and offices",
    longDescription:
      "Perfect for kitchens and offices, this counter-top dispenser provides instant access to hot and cold water. Compact design fits any space.",
    features: ["Compact design", "Hot & Cold water", "Energy efficient", "Easy installation"],
    specifications: {
      Type: "Counter Top",
      Capacity: "5-10L",
      Temperature: "Hot & Cold",
      Power: "500W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "standing-dispenser",
    name: "Standing Dispenser",
    category: "Dispensers",
    subcategory: "Water Dispensers",
    price: "From AED 799",
    description: "Floor-standing water dispenser with large capacity",
    longDescription:
      "Professional-grade standing dispenser ideal for offices, gyms, and commercial spaces. Features large water capacity and efficient cooling system.",
    features: ["Large capacity", "Professional design", "Efficient cooling", "Multiple taps"],
    specifications: {
      Type: "Standing",
      Capacity: "20L",
      Temperature: "Hot & Cold",
      Power: "800W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Pumps
  {
    id: "dosing-pump",
    name: "Dosing Pump",
    category: "Pumps & Accessories",
    subcategory: "Pumps",
    price: "From AED 299",
    description: "Precision dosing pump for chemical injection",
    longDescription:
      "High-precision dosing pump for injecting chemicals like antiscalant and pH adjusters in RO systems. Reliable and accurate dosing.",
    features: ["Precise dosing", "Durable construction", "Easy installation", "Low maintenance"],
    specifications: {
      Type: "Dosing",
      Flow: "0.5-2 GPH",
      Pressure: "100 PSI",
      Material: "Plastic",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "booster-pump",
    name: "Booster Pump",
    category: "Pumps & Accessories",
    subcategory: "Pumps",
    price: "From AED 899",
    description: "High-pressure booster pump for RO systems",
    longDescription:
      "Essential for low-pressure water supply areas. Increases water pressure to optimal levels for efficient RO filtration. Reliable and energy-efficient.",
    features: ["High pressure output", "Energy efficient", "Quiet operation", "Long lifespan"],
    specifications: {
      Type: "Booster",
      Output: "50 PSI",
      Power: "400W",
      Flow: "100 GPD",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "grundfos-pump",
    name: "Grundfos Pump",
    category: "Pumps & Accessories",
    subcategory: "Pumps",
    price: "From AED 1,299",
    description: "Premium Grundfos water pump for commercial systems",
    longDescription:
      "Professional-grade Grundfos pump for large-scale water filtration systems. Known for reliability and efficiency in commercial applications.",
    features: ["Premium quality", "High efficiency", "Durable", "Professional grade"],
    specifications: {
      Type: "Centrifugal",
      Power: "750W",
      Flow: "200 GPM",
      Head: "100 feet",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "lubi-pump",
    name: "Lubi Pump",
    category: "Pumps & Accessories",
    subcategory: "Pumps",
    price: "From AED 1,099",
    description: "Reliable Lubi water pump for RO systems",
    longDescription:
      "Trusted Lubi pump for residential and commercial RO systems. Provides consistent pressure and reliable performance.",
    features: ["Reliable", "Cost-effective", "Good performance", "Easy maintenance"],
    specifications: {
      Type: "Centrifugal",
      Power: "600W",
      Flow: "150 GPM",
      Head: "80 feet",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Filters
  {
    id: "single-stage-2-5x10",
    name: "Single Stage 2.5 x 10 Filter",
    category: "Filter Cartridges",
    subcategory: "Sediment Filters",
    price: "From AED 49",
    description: "Single stage sediment filter cartridge",
    longDescription:
      "Standard sediment filter for removing large particles and sediment. Essential first stage in any water filtration system.",
    features: ["Effective sediment removal", "Long lifespan", "Easy replacement", "Cost-effective"],
    specifications: {
      Size: "2.5 x 10 inches",
      Micron: "5 micron",
      Flow: "20 GPM",
      Lifespan: "3-6 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "two-stage-10",
    name: "Two Stage 10 Inch Filter",
    category: "Filter Cartridges",
    subcategory: "Multi-Stage Filters",
    price: "From AED 89",
    description: "Two-stage filter cartridge for enhanced filtration",
    longDescription:
      "Combines sediment and carbon filtration in one cartridge. Removes particles, chlorine, and odors effectively.",
    features: ["Dual filtration", "Removes chlorine", "Better water quality", "Longer lifespan"],
    specifications: {
      Size: "10 inches",
      Stages: "2",
      Flow: "20 GPM",
      Lifespan: "6-9 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "three-stage-10",
    name: "Three Stage 10 Inch Filter",
    category: "Filter Cartridges",
    subcategory: "Multi-Stage Filters",
    price: "From AED 129",
    description: "Three-stage filter for comprehensive water treatment",
    longDescription:
      "Advanced three-stage filtration removes sediment, chlorine, and odors. Ideal for whole-house systems and pre-filtration.",
    features: ["Triple filtration", "Comprehensive treatment", "Excellent quality", "Extended lifespan"],
    specifications: {
      Size: "10 inches",
      Stages: "3",
      Flow: "20 GPM",
      Lifespan: "9-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "single-20",
    name: "Single Stage 20 Inch Filter",
    category: "Filter Cartridges",
    subcategory: "Sediment Filters",
    price: "From AED 79",
    description: "Large single stage 20-inch sediment filter",
    longDescription:
      "High-capacity sediment filter for commercial and industrial applications. Handles higher flow rates efficiently.",
    features: ["High capacity", "Commercial grade", "Long lifespan", "Cost-effective"],
    specifications: {
      Size: "20 inches",
      Micron: "5 micron",
      Flow: "50 GPM",
      Lifespan: "6-9 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "three-stage-20",
    name: "Three Stage 20 Inch Filter",
    category: "Filter Cartridges",
    subcategory: "Multi-Stage Filters",
    price: "From AED 199",
    description: "Three-stage 20-inch filter for high-volume filtration",
    longDescription:
      "Professional-grade three-stage filter for commercial systems. Excellent for high-volume water treatment requirements.",
    features: ["High capacity", "Triple filtration", "Professional grade", "Extended lifespan"],
    specifications: {
      Size: "20 inches",
      Stages: "3",
      Flow: "50 GPM",
      Lifespan: "12-15 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "pp-yarn",
    name: "PP Yarn Filter",
    category: "Filter Cartridges",
    subcategory: "Sediment Filters",
    price: "From AED 39",
    description: "Polypropylene yarn wound filter cartridge",
    longDescription:
      "Effective sediment filter using polypropylene yarn. Removes particles and improves water clarity.",
    features: ["Effective sediment removal", "Affordable", "Easy replacement", "Good flow rate"],
    specifications: {
      Material: "PP Yarn",
      Micron: "5-10 micron",
      Flow: "20 GPM",
      Lifespan: "3-6 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "pp-spun",
    name: "PP Spun Filter",
    category: "Filter Cartridges",
    subcategory: "Sediment Filters",
    price: "From AED 49",
    description: "Polypropylene spun filter cartridge",
    longDescription:
      "High-quality spun polypropylene filter for sediment removal. Better dirt-holding capacity than yarn filters.",
    features: ["Better capacity", "Uniform filtration", "Reliable", "Cost-effective"],
    specifications: {
      Material: "PP Spun",
      Micron: "5-20 micron",
      Flow: "20 GPM",
      Lifespan: "4-8 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "cto-filter",
    name: "CTO (Carbon Block) Filter",
    category: "Filter Cartridges",
    subcategory: "Carbon Filters",
    price: "From AED 59",
    description: "Carbon block filter for chlorine and odor removal",
    longDescription:
      "Activated carbon block filter effectively removes chlorine, odors, and improves water taste. Essential for pre-filtration.",
    features: ["Removes chlorine", "Improves taste", "Odor removal", "Long lasting"],
    specifications: {
      Material: "Carbon Block",
      Micron: "5 micron",
      Flow: "20 GPM",
      Lifespan: "6-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "gac-filter",
    name: "GAC (Granular Activated Carbon) Filter",
    category: "Filter Cartridges",
    subcategory: "Carbon Filters",
    price: "From AED 69",
    description: "Granular activated carbon filter cartridge",
    longDescription:
      "Loose granular activated carbon for superior chlorine and odor removal. Ideal for whole-house systems.",
    features: ["Superior filtration", "Chlorine removal", "Taste improvement", "Cost-effective"],
    specifications: {
      Material: "GAC",
      Size: "10 inches",
      Flow: "20 GPM",
      Lifespan: "6-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "pleated-filter",
    name: "Pleated Filter Cartridge",
    category: "Filter Cartridges",
    subcategory: "Sediment Filters",
    price: "From AED 89",
    description: "High-capacity pleated filter cartridge",
    longDescription:
      "Pleated design provides large filtration area. Excellent for removing fine particles and sediment.",
    features: ["Large surface area", "Fine filtration", "Long lifespan", "High capacity"],
    specifications: {
      Design: "Pleated",
      Micron: "1-10 micron",
      Flow: "30 GPM",
      Lifespan: "9-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "high-flow-filter",
    name: "High Flow Filter",
    category: "Filter Cartridges",
    subcategory: "Specialty Filters",
    price: "From AED 149",
    description: "High-capacity filter for commercial applications",
    longDescription:
      "Designed for high-volume water treatment. Maintains excellent flow rates while providing effective filtration.",
    features: ["High flow rate", "Commercial grade", "Durable", "Professional quality"],
    specifications: {
      Capacity: "100+ GPM",
      Micron: "5-20 micron",
      Material: "Multi-layer",
      Lifespan: "12-18 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // RO Membranes & Components
  {
    id: "ro-membrane-4",
    name: "RO Membrane 4 Inch",
    category: "RO Components",
    subcategory: "RO Membranes",
    price: "From AED 199",
    description: "4-inch RO membrane (Filmtec)",
    longDescription:
      "High-quality Filmtec RO membrane for residential systems. Removes 99% of dissolved solids and contaminants.",
    features: ["Filmtec quality", "High rejection rate", "Long lifespan", "Reliable"],
    specifications: {
      Size: "4 inches",
      Type: "Filmtec",
      Flow: "50 GPD",
      Rejection: "99%",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "ro-membrane-8",
    name: "RO Membrane 8 Inch",
    category: "RO Components",
    subcategory: "RO Membranes",
    price: "From AED 349",
    description: "8-inch RO membrane (Filmtec)",
    longDescription:
      "Professional-grade 8-inch RO membrane for commercial systems. High flow rate with excellent rejection.",
    features: ["High capacity", "Professional grade", "Excellent rejection", "Long lasting"],
    specifications: {
      Size: "8 inches",
      Type: "Filmtec",
      Flow: "100 GPD",
      Rejection: "99%",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "pressure-vessel-1e-600",
    name: "Pressure Vessel 1E 600PSI",
    category: "RO Components",
    subcategory: "Pressure Vessels",
    price: "From AED 299",
    description: "Single element pressure vessel 600 PSI",
    longDescription:
      "Durable pressure vessel for single RO membrane. Rated for 600 PSI operation. Essential component for RO systems.",
    features: ["High pressure rated", "Durable construction", "Easy maintenance", "Professional grade"],
    specifications: {
      Elements: "1",
      Pressure: "600 PSI",
      Material: "Fiberglass",
      Size: "2.5 x 10 inches",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "pressure-vessel-2e-600",
    name: "Pressure Vessel 2E 600PSI",
    category: "RO Components",
    subcategory: "Pressure Vessels",
    price: "From AED 499",
    description: "Dual element pressure vessel 600 PSI",
    longDescription:
      "Professional pressure vessel for two RO membranes. High capacity for commercial applications.",
    features: ["Dual element", "High capacity", "Professional grade", "Reliable"],
    specifications: {
      Elements: "2",
      Pressure: "600 PSI",
      Material: "Fiberglass",
      Size: "4 x 10 inches",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "pressure-vessel-3e-600",
    name: "Pressure Vessel 3E 600PSI",
    category: "RO Components",
    subcategory: "Pressure Vessels",
    price: "From AED 699",
    description: "Triple element pressure vessel 600 PSI",
    longDescription:
      "High-capacity pressure vessel for three RO membranes. Ideal for large commercial and industrial systems.",
    features: ["Triple element", "Very high capacity", "Industrial grade", "Durable"],
    specifications: {
      Elements: "3",
      Pressure: "600 PSI",
      Material: "Fiberglass",
      Size: "6 x 10 inches",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Water Treatment Chemicals
  {
    id: "antiscalant",
    name: "Antiscalant Solution",
    category: "Chemicals",
    subcategory: "Water Treatment",
    price: "From AED 149",
    description: "Antiscalant chemical for RO systems",
    longDescription:
      "Prevents mineral scale buildup in RO membranes. Extends membrane lifespan and improves system efficiency.",
    features: ["Prevents scaling", "Extends membrane life", "Improves efficiency", "Cost-effective"],
    specifications: {
      Type: "Liquid",
      Volume: "1 Liter",
      Dosage: "2-5 PPM",
      ShelfLife: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "softener-resin",
    name: "Softener Resin",
    category: "Chemicals",
    subcategory: "Water Softening",
    price: "From AED 399",
    description: "Ion exchange resin for water softeners",
    longDescription:
      "Premium ion exchange resin for removing hardness minerals. Regenerable and long-lasting.",
    features: ["High capacity", "Long lifespan", "Regenerable", "Effective hardness removal"],
    specifications: {
      Type: "Cation Exchange",
      Capacity: "30,000 grains/liter",
      Volume: "25 kg bag",
      Lifespan: "3-5 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "soft-salt",
    name: "Soft Salt (Regeneration Salt)",
    category: "Chemicals",
    subcategory: "Water Softening",
    price: "From AED 29",
    description: "Salt for water softener regeneration",
    longDescription:
      "Pure salt for regenerating water softener resin. Ensures optimal softening performance.",
    features: ["Pure quality", "Effective regeneration", "Affordable", "Available in bulk"],
    specifications: {
      Type: "NaCl",
      Purity: "99.5%",
      Weight: "25 kg",
      Density: "High density",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Tanks & Storage
  {
    id: "ro-dispenser-tank",
    name: "RO Dispenser Tank",
    category: "Tanks & Storage",
    subcategory: "Water Tanks",
    price: "From AED 199",
    description: "Stainless steel RO dispenser tank",
    longDescription:
      "Durable stainless steel tank for storing filtered water. Maintains water quality and prevents contamination.",
    features: ["Stainless steel", "Hygienic", "Durable", "Easy installation"],
    specifications: {
      Material: "Stainless Steel",
      Capacity: "10-20 liters",
      Type: "Dispenser",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "ro-tank",
    name: "RO Storage Tank",
    category: "Tanks & Storage",
    subcategory: "Water Tanks",
    price: "From AED 249",
    description: "High-quality RO storage tank",
    longDescription:
      "Food-grade plastic RO storage tank. Maintains water freshness and prevents bacterial growth.",
    features: ["Food grade", "Durable", "Large capacity", "Easy maintenance"],
    specifications: {
      Material: "Food Grade Plastic",
      Capacity: "20-50 liters",
      Type: "Storage",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "water-chiller",
    name: "Water Chiller",
    category: "Tanks & Storage",
    subcategory: "Water Coolers",
    price: "From AED 799",
    description: "Electric water chiller for instant cold water",
    longDescription:
      "Compact water chiller for instant cold water supply. Perfect for offices and homes.",
    features: ["Instant cooling", "Energy efficient", "Compact design", "Easy installation"],
    specifications: {
      Type: "Electric",
      Capacity: "10-20 liters",
      Temperature: "4-8°C",
      Power: "300W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // KENT Products
  {
    id: "kent-excel-plus",
    name: "KENT Excel Plus RO",
    category: "Complete Systems",
    subcategory: "KENT Products",
    price: "From AED 1,299",
    description: "KENT Excel Plus RO+UV+UF system",
    longDescription:
      "Most popular KENT RO system with advanced RO+UV+UF technology. TDS controller and mineral retention.",
    features: ["RO+UV+UF", "TDS Controller", "Mineral retention", "1-year warranty"],
    specifications: {
      Technology: "RO+UV+UF",
      Capacity: "10-15 liters/hour",
      Warranty: "1 year",
    },
    image: "/images/ro-installation.jpg",
    badge: "Popular",
    inStock: true,
  },
  {
    id: "kent-sterling-plus",
    name: "KENT Sterling Plus RO",
    category: "Complete Systems",
    subcategory: "KENT Products",
    price: "From AED 1,099",
    description: "KENT Sterling Plus compact RO system",
    longDescription:
      "Compact and efficient RO system from KENT. Perfect for small homes and apartments.",
    features: ["Compact design", "RO+UV+UF", "Water saving", "Easy installation"],
    specifications: {
      Technology: "RO+UV+UF",
      Capacity: "8-12 liters/hour",
      Warranty: "1 year",
      Design: "Compact",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "kent-grand-plus",
    name: "KENT Grand Plus RO",
    category: "Complete Systems",
    subcategory: "KENT Products",
    price: "From AED 1,399",
    description: "KENT Grand Plus with mineral RO technology",
    longDescription:
      "Premium KENT system with transparent design. Mineral RO technology retains essential minerals.",
    features: ["Mineral RO", "Transparent design", "TDS Controller", "Premium quality"],
    specifications: {
      Technology: "Mineral RO",
      Capacity: "12-18 liters/hour",
      Warranty: "2 years",
      Design: "Transparent",
    },
    image: "/images/ro-installation.jpg",
    badge: "Premium",
    inStock: true,
  },
  {
    id: "kent-smart-alkaline",
    name: "KENT Smart Alkaline RO",
    category: "Complete Systems",
    subcategory: "KENT Products",
    price: "From AED 1,599",
    description: "KENT Smart Alkaline with pH+ technology",
    longDescription:
      "Advanced KENT system with alkaline water technology. Adds essential minerals and maintains pH balance.",
    features: ["Alkaline water", "pH+ technology", "Mineral retention", "Smart features"],
    specifications: {
      Technology: "RO+Alkaline",
      Capacity: "15-20 liters/hour",
      Warranty: "2 years",
      Features: "Smart controls",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Accessories
  {
    id: "ro-pipe-1-4",
    name: "RO Pipe 1/4 Inch",
    category: "Accessories",
    subcategory: "Pipes & Fittings",
    price: "From AED 2/meter",
    description: "Food-grade RO pipe 1/4 inch diameter",
    longDescription:
      "Durable food-grade plastic pipe for RO system connections. Safe for drinking water applications.",
    features: ["Food grade", "Durable", "Easy installation", "Flexible"],
    specifications: {
      Size: "1/4 inch",
      Material: "Food Grade Plastic",
      Length: "Per meter",
      Pressure: "100 PSI",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "ro-pipe-3-8",
    name: "RO Pipe 3/8 Inch",
    category: "Accessories",
    subcategory: "Pipes & Fittings",
    price: "From AED 3/meter",
    description: "Food-grade RO pipe 3/8 inch diameter",
    longDescription:
      "Larger diameter RO pipe for higher flow applications. Food-grade and pressure-rated.",
    features: ["Food grade", "Higher flow", "Durable", "Professional grade"],
    specifications: {
      Size: "3/8 inch",
      Material: "Food Grade Plastic",
      Length: "Per meter",
      Pressure: "100 PSI",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "mini-softener",
    name: "Mini Softener System",
    category: "Accessories",
    subcategory: "Water Softening",
    price: "From AED 1,299",
    description: "Compact water softener for homes",
    longDescription:
      "Compact water softening system for removing hardness. Perfect for homes with hard water.",
    features: ["Compact", "Effective", "Easy regeneration", "Affordable"],
    specifications: {
      Type: "Ion Exchange",
      Capacity: "10,000 grains",
      Size: "Compact",
      Warranty: "1 year",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "inline-post-carbon",
    name: "Inline Post Carbon Filter",
    category: "Accessories",
    subcategory: "Inline Filters",
    price: "From AED 79",
    description: "Inline post-filtration carbon filter",
    longDescription:
      "Final stage carbon filter for polishing water taste. Connects directly to RO faucet.",
    features: ["Final polishing", "Improves taste", "Easy installation", "Long lasting"],
    specifications: {
      Type: "Inline Carbon",
      Size: "2.5 x 10 inches",
      Flow: "20 GPM",
      Lifespan: "6-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "inline-pp-sediment",
    name: "Inline PP Sediment Filter",
    category: "Accessories",
    subcategory: "Inline Filters",
    price: "From AED 39",
    description: "Inline sediment filter cartridge",
    longDescription:
      "Quick-connect inline sediment filter for RO systems. Removes fine particles before final stage.",
    features: ["Inline design", "Quick connect", "Effective", "Easy replacement"],
    specifications: {
      Type: "Inline Sediment",
      Micron: "5 micron",
      Flow: "20 GPM",
      Lifespan: "3-6 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "inline-cto",
    name: "Inline CTO Filter",
    category: "Accessories",
    subcategory: "Inline Filters",
    price: "From AED 59",
    description: "Inline carbon block filter",
    longDescription:
      "Inline carbon filter for chlorine and odor removal. Easy installation and replacement.",
    features: ["Inline design", "Chlorine removal", "Quick connect", "Effective"],
    specifications: {
      Type: "Inline Carbon",
      Micron: "5 micron",
      Flow: "20 GPM",
      Lifespan: "6-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "inline-gac",
    name: "Inline GAC Filter",
    category: "Accessories",
    subcategory: "Inline Filters",
    price: "From AED 69",
    description: "Inline granular activated carbon filter",
    longDescription:
      "Inline GAC filter for superior water polishing. Removes remaining contaminants and improves taste.",
    features: ["Inline design", "Superior filtration", "Quick connect", "Long lasting"],
    specifications: {
      Type: "Inline GAC",
      Size: "2.5 x 10 inches",
      Flow: "20 GPM",
      Lifespan: "6-12 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Shower Filters
  {
    id: "shower-filter",
    name: "Shower Filter",
    category: "Specialty Filters",
    subcategory: "Shower Filters",
    price: "From AED 199",
    description: "Chlorine removal shower filter",
    longDescription:
      "Removes chlorine and impurities from shower water. Protects skin and hair from harsh chemicals.",
    features: ["Chlorine removal", "Skin protection", "Easy installation", "Replaceable cartridge"],
    specifications: {
      Type: "Shower Filter",
      Cartridge: "Replaceable",
      Flow: "2.5 GPM",
      Lifespan: "6 months",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "shower-filter-head",
    name: "Shower Filter Head",
    category: "Specialty Filters",
    subcategory: "Shower Filters",
    price: "From AED 149",
    description: "Replacement shower filter head",
    longDescription:
      "Replacement head for shower filter systems. Easy installation and compatible with most systems.",
    features: ["Replacement part", "Easy installation", "Durable", "Cost-effective"],
    specifications: {
      Type: "Shower Head",
      Material: "Chrome plated",
      Flow: "2.5 GPM",
      Compatibility: "Universal",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // UV & UF Systems
  {
    id: "uv-system",
    name: "UV Sterilization System",
    category: "Advanced Filtration",
    subcategory: "UV Systems",
    price: "From AED 399",
    description: "UV sterilizer for water disinfection",
    longDescription:
      "Ultraviolet sterilization system kills bacteria and viruses. Essential for complete water purification.",
    features: ["Kills bacteria", "Virus removal", "Chemical-free", "Long lasting"],
    specifications: {
      Type: "UV",
      Power: "11W",
      Flow: "20 GPM",
      Lifespan: "1 year",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "uf-nano-filter",
    name: "UF Nano Filter",
    category: "Advanced Filtration",
    subcategory: "UF Systems",
    price: "From AED 299",
    description: "Ultrafiltration nano filter",
    longDescription:
      "Advanced ultrafiltration technology removes bacteria and viruses. Complements RO systems.",
    features: ["Nano filtration", "Bacteria removal", "High efficiency", "Durable"],
    specifications: {
      Type: "UF Nano",
      Micron: "0.01 micron",
      Flow: "20 GPM",
      Lifespan: "2-3 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Whole House Systems
  {
    id: "whole-house-200",
    name: "Whole House RO System 200 GPD",
    category: "Complete Systems",
    subcategory: "Whole House Systems",
    price: "From AED 2,499",
    description: "Whole house RO system 200 GPD capacity",
    longDescription:
      "Complete whole-house RO system for entire home water supply. 200 GPD capacity suitable for families.",
    features: ["Whole house", "200 GPD", "Complete system", "Professional installation"],
    specifications: {
      Capacity: "200 GPD",
      Stages: "5",
      Type: "Whole House",
      Installation: "Professional",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "whole-house-400",
    name: "Whole House RO System 400 GPD",
    category: "Complete Systems",
    subcategory: "Whole House Systems",
    price: "From AED 3,999",
    description: "Whole house RO system 400 GPD capacity",
    longDescription:
      "High-capacity whole-house RO system for larger families and small businesses.",
    features: ["High capacity", "400 GPD", "Professional grade", "Complete solution"],
    specifications: {
      Capacity: "400 GPD",
      Stages: "5",
      Type: "Whole House",
      Installation: "Professional",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "whole-house-800",
    name: "Whole House RO System 800 GPD",
    category: "Complete Systems",
    subcategory: "Whole House Systems",
    price: "From AED 6,499",
    description: "Industrial whole house RO system 800 GPD",
    longDescription:
      "Industrial-grade whole-house RO system for large families, hotels, and commercial facilities.",
    features: ["Industrial grade", "800 GPD", "High capacity", "Professional quality"],
    specifications: {
      Capacity: "800 GPD",
      Stages: "5",
      Type: "Whole House",
      Installation: "Professional",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Cabinet Systems
  {
    id: "cabinet-ro-system",
    name: "Cabinet RO System",
    category: "Complete Systems",
    subcategory: "Cabinet Systems",
    price: "From AED 1,899",
    description: "Under-counter cabinet RO system",
    longDescription:
      "Compact under-counter RO system with cabinet storage. Perfect for kitchens with space constraints.",
    features: ["Under counter", "Cabinet design", "Space saving", "Complete system"],
    specifications: {
      Type: "Cabinet RO",
      Capacity: "50 GPD",
      Installation: "Under counter",
      Warranty: "1 year",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Bag Filters
  {
    id: "bag-filter-7x17",
    name: "Bag Filter 7x17 Inch",
    category: "Industrial Filters",
    subcategory: "Bag Filters",
    price: "From AED 99",
    description: "Large bag filter for industrial use",
    longDescription:
      "Industrial-grade bag filter for high-volume water treatment. Effective sediment removal.",
    features: ["Industrial grade", "Large capacity", "Effective", "Durable"],
    specifications: {
      Size: "7 x 17 inches",
      Micron: "5-100 micron",
      Capacity: "High",
      Material: "Polypropylene",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "bag-filter-7x32",
    name: "Bag Filter 7x32 Inch",
    category: "Industrial Filters",
    subcategory: "Bag Filters",
    price: "From AED 149",
    description: "Extra large bag filter for industrial applications",
    longDescription:
      "Extra-large bag filter for maximum sediment removal capacity. Ideal for industrial systems.",
    features: ["Extra large", "Very high capacity", "Professional grade", "Durable"],
    specifications: {
      Size: "7 x 32 inches",
      Micron: "5-100 micron",
      Capacity: "Very high",
      Material: "Polypropylene",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Water Coolers
  {
    id: "water-cooler-2-tap",
    name: "Water Cooler 2 Tap",
    category: "Dispensers",
    subcategory: "Water Coolers",
    price: "From AED 699",
    description: "2-tap water cooler (hot & cold)",
    longDescription:
      "Professional 2-tap water cooler for offices. Provides hot and cold water on demand.",
    features: ["2 taps", "Hot & cold", "Professional", "Energy efficient"],
    specifications: {
      Taps: "2",
      Temperature: "Hot & Cold",
      Capacity: "20L",
      Power: "600W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "water-cooler-3-tap",
    name: "Water Cooler 3 Tap",
    category: "Dispensers",
    subcategory: "Water Coolers",
    price: "From AED 799",
    description: "3-tap water cooler with room temperature option",
    longDescription:
      "Advanced 3-tap water cooler with hot, cold, and room temperature options.",
    features: ["3 taps", "Hot/Cold/Room temp", "Professional", "Versatile"],
    specifications: {
      Taps: "3",
      Temperature: "Hot/Cold/Room",
      Capacity: "20L",
      Power: "700W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "water-cooler-4-tap",
    name: "Water Cooler 4 Tap",
    category: "Dispensers",
    subcategory: "Water Coolers",
    price: "From AED 899",
    description: "4-tap water cooler with multiple options",
    longDescription:
      "Premium 4-tap water cooler with maximum flexibility. Perfect for busy offices.",
    features: ["4 taps", "Multiple options", "Premium", "Professional grade"],
    specifications: {
      Taps: "4",
      Temperature: "Hot/Cold/Room/Chilled",
      Capacity: "20L",
      Power: "800W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "water-cooler-5-tap",
    name: "Water Cooler 5 Tap",
    category: "Dispensers",
    subcategory: "Water Coolers",
    price: "From AED 1,099",
    description: "5-tap water cooler with all options",
    longDescription:
      "Top-of-the-line 5-tap water cooler with all temperature options. Maximum versatility.",
    features: ["5 taps", "All options", "Premium quality", "Professional grade"],
    specifications: {
      Taps: "5",
      Temperature: "All options",
      Capacity: "20L",
      Power: "900W",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // P90 & Specialty
  {
    id: "p90-system",
    name: "P90 Water Purification System",
    category: "Complete Systems",
    subcategory: "Specialty Systems",
    price: "From AED 1,799",
    description: "Advanced P90 water purification system",
    longDescription:
      "Advanced P90 system with multiple filtration stages. Removes 99.9% of contaminants.",
    features: ["Advanced technology", "99.9% removal", "Efficient", "Reliable"],
    specifications: {
      Technology: "P90",
      Stages: "9",
      Capacity: "20 liters/hour",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // UPVC Multicartridge
  {
    id: "upvc-multicartridge",
    name: "UPVC/SS Multicartridge Housing",
    category: "RO Components",
    subcategory: "Filter Housings",
    price: "From AED 399",
    description: "UPVC or stainless steel multicartridge housing",
    longDescription:
      "Durable multicartridge housing for multiple filter stages. Available in UPVC or stainless steel.",
    features: ["Durable", "Multiple cartridges", "Professional grade", "Easy maintenance"],
    specifications: {
      Material: "UPVC/SS",
      Cartridges: "Multiple",
      Pressure: "100 PSI",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Nano Filter
  {
    id: "nano-filter",
    name: "Nano Filter Cartridge",
    category: "Advanced Filtration",
    subcategory: "Nano Filters",
    price: "From AED 249",
    description: "Advanced nano filter technology",
    longDescription:
      "Cutting-edge nano filter technology for superior water purification. Removes bacteria and viruses.",
    features: ["Nano technology", "Superior filtration", "Long lasting", "Efficient"],
    specifications: {
      Type: "Nano Filter",
      Micron: "0.001 micron",
      Flow: "20 GPM",
      Lifespan: "2-3 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },

  // Clack & Brine Tank
  {
    id: "clack-valve",
    name: "Clack Water Softener Valve",
    category: "Water Softening",
    subcategory: "Softener Components",
    price: "From AED 1,299",
    description: "Clack automatic softener valve",
    longDescription:
      "Premium Clack automatic valve for water softeners. Reliable and efficient regeneration.",
    features: ["Automatic", "Reliable", "Efficient", "Professional grade"],
    specifications: {
      Brand: "Clack",
      Type: "Automatic Valve",
      Flow: "20 GPM",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "brine-tank",
    name: "Brine Tank for Water Softener",
    category: "Water Softening",
    subcategory: "Softener Components",
    price: "From AED 399",
    description: "Brine tank for salt storage",
    longDescription:
      "Durable brine tank for storing regeneration salt. Essential component for water softeners.",
    features: ["Durable", "Salt storage", "Easy maintenance", "Long lasting"],
    specifications: {
      Material: "Plastic",
      Capacity: "50-100 kg salt",
      Type: "Brine Tank",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
  {
    id: "kent-gem",
    name: "KENT Gem Water Softener",
    category: "Water Softening",
    subcategory: "KENT Products",
    price: "From AED 1,499",
    description: "KENT Gem water softener system",
    longDescription:
      "Premium KENT water softener for effective hardness removal. Compact and efficient design.",
    features: ["KENT quality", "Effective", "Compact", "Reliable"],
    specifications: {
      Brand: "KENT",
      Type: "Water Softener",
      Capacity: "10,000 grains",
      Warranty: "2 years",
    },
    image: "/images/ro-installation.jpg",
    inStock: true,
  },
];
